export const GET_GUARDIANLIST = "GET_GUARDIANLIST";
export const GET_GUARDIANDETAIL = "GET_GUARDIANDETAIL";
export const GET_GUARDIANSEARCH = "GET_GUARDIANSEARCH";
export const GET_GUARDIANSDATESEARCH = "GET_GUARDIANSDATESEARCH";








